title:               Learning FinTech
url:                 https://learning-fintech.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              James Nordlund
  url:               jamesnordlund.github.io
  email:             james@nordlund.ai

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
